### ISSUE TITLE
Project ETA

### ISSUE THREAD

**Issue by mytototo** [BlazingDB/blazing-jdbc#1]
Hi,

Is this project still active?
Can we use it as a `jdbc` input/output in Logstash?

Thanks.

**Comment by felipeblazing** [comment]
We have not tried it ourselves. If you would like to try connecting it in this way (do not enable paging) we would be happy to help you along the process. If you have issues let us know here: https://docs.blazingdb.com/discuss

FYI we are getting more and more interest in using the JDBC driver for connectivity and should be dedicating resources to increasing its capabilities in the next few weeks.

**Comment by mytototo** [comment]
Thanks for your quick answer @felipeblazing I appreciate. I'll probably give it a try in the next few days.

My goal is to use this plugin inside Logstash to ETL from a PostgreSQL database (input) to a BlazingDB database (output). Does that make sense?

**Comment by felipeblazing** [comment]
No worries @mytototo . So I am not exactly sure what state it is in but we have an ETL tool from Postgres to Blazing that runs in ptyhon. It might need to be tweaked a little but those fixes should be easy to make (or if you find any errors you can let us know and we will fix them.) You can find that here https://github.com/BlazingDB/python-connector (the third example is migrating from postgres)

**Comment by felipeblazing** [comment]
@mytototo let me know if you want to have a chat about what you are trying to do with BlazingDB.

**Comment by mytototo** [comment]
I see... I wanted to use Logstash to be more flexible with the data pipeline.
Thanks for your support but I'm fine for now. Just giving a try.
